backend:
  name: github
  repo: kuldar/garaazid-web

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: "garages"
    label: "Garages"
    folder: "src/garages"
    extension: "yaml"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Aadress", name: "address", widget: "string" }
      - { label: "Hind (Rent)", name: "rentPrice", widget: "number" }
      - { label: "Hind (Müük)", name: "sellPrice", widget: "number" }
      - { label: "Pindala (m²)", name: "area", widget: "number" }
      - { label: "Lühikirjeldus", name: "shortDescription", widget: "string" }
      - { label: "Kirjeldus", name: "description", widget: "markdown" }
      - { label: "Kaanepilt", name: "coverImage", widget: "image" }