backend:
  name: test-repo
  # name: github
  # repo: kuldar/garaazid-web

media_folder: static/img
public_folder: /img

collections:
  - name: "garages"
    label: "Garages"
    folder: "src/garages"
    extension: "yaml"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Address", name: "address", widget: "string" }
      - { label: "Area", name: "area", widget: "" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Featured Image", name: "featuredimage", widget: "image" }