development_overrides:
  backend:
    name: file-system
    api_root: /api

backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: "garages"
    label: "Garaazid"
    folder: "src/garages"
    extension: "yml"
    slug: "{{slug}}"
    create: true
    editor:
      preview: false
    identifier_field: id
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Aadress", name: "address", widget: "string", tagname: h1 }
      - { label: "Hind (Rent)", name: "rentPrice", widget: "number", required: false }
      - { label: "Hind (Müük)", name: "sellPrice", widget: "number", required: false }
      - { label: "Pindala (m²)", name: "area", widget: "number", required: false }
      - { label: "Lühikirjeldus", name: "shortDescription", widget: "string" }
      - { label: "Kirjeldus", name: "description", widget: "markdown" }
      - { label: "Kaanepilt", name: "coverImage", widget: "image" }
      - { label: "Pildid", name: "images", widget: "list", field: { label: Pilt, name: image, widget: image }}